services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - backend

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - mlflow_data:/mlruns
      - ./scripts:/app/scripts

volumes:
  postgres_data:
    name: postgres_data_vol
  pgadmin_data:
    name: pgadmin_data_vol
  mlflow_data:
    name: mlflow_data

networks:
  backend: