services:
  postgres:
    image: postgres:15.4
    container_name: ml_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_pass
      POSTGRES_DB: ml_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sample-dbs/titanic.sql:/docker-entrypoint-initdb.d/titanic.sql

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    container_name: mlflow_server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

volumes:
  postgres_data:
  pgadmin_data:
